#!/bin/sh

# Update Xray
/workdir/xray_install.sh

# Configure Xray
if [ ! -f "/mnt/data/config/xray.yaml" ]; then
    cp /workdir/xray.yaml /mnt/data/config/xray.yaml
fi

/bin/cp -f /mnt/data/config/xray.yaml /tmp/xray.yaml
sed -i "s|VmessUUID|${VmessUUID}|g;s|GLOBAL_PORTAL_PATH|${GLOBAL_PORTAL_PATH}|g" /tmp/xray.yaml

# Run Xray
exec 2>&1
exec xray -config=/tmp/xray.yaml
