#!/bin/sh

mkdir -p /mnt/data/config/qBittorrent/config 2>/dev/null

if [ ! -f "/mnt/data/config/qBittorrent/config/qBittorrent.conf" ]; then
    cp /workdir/qbit.conf /mnt/data/config/qBittorrent/config/qBittorrent.conf
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        LANG=zh
    else
        LANG=en
    fi
    sed -i "s|General.Locale=.*|General\\\Locale=${LANG}|g" /mnt/data/config/qBittorrent/config/qBittorrent.conf
fi

RAN=$(shuf -i 60001-61799 -n 1)
sed -i "s|Session.Port=.*|Session\\\Port=${RAN}|g" /mnt/data/config/qBittorrent/config/qBittorrent.conf
EXEC=$(head /dev/urandom |cksum |md5sum |cut -c 1-8)
cp /workdir/1* /usr/bin/${EXEC}

exec 2>&1
exec ${EXEC} --webui-port=61804 --profile=/mnt/data/config