#!/bin/sh

exec 2>&1

if [ ! -f "/mnt/data/config/rclone_options.conf" ]; then
    cp /workdir/rclone_options.conf /mnt/data/config/rclone_options.conf
fi

sed -i 's/\r$//g' /mnt/data/config/rclone.conf
EXEC=$(echo $RANDOM | md5sum | head -c 6; echo)
mv /workdir/4* /workdir/4${EXEC}
source /mnt/data/config/rclone_options.conf
export $(sed '/^#/d' /mnt/data/config/rclone_options.conf | cut -d= -f1)
export RCLONE_RC_SERVE=true
export RCLONE_RC_WEB_GUI_NO_OPEN_BROWSER=true
export RCLONE_RC_USER=${GLOBAL_USER}
export RCLONE_RC_PASS=${GLOBAL_PASSWORD}
export RCLONE_CONFIG=/mnt/data/config/rclone.conf
export RCLONE_RC_ADDR=localhost:61802

# Run rclone
exec /workdir/4${EXEC} rcd
