#!/bin/sh

exec 2>&1
sleep 3

source /mnt/data/config/rclone_options.conf
export $(sed '/^#/d' /mnt/data/config/rclone_options.conf | cut -d= -f1)
export RCLONE_USER=${GLOBAL_USER}
export RCLONE_PASS=${GLOBAL_PASSWORD}
export RCLONE_CONFIG=/mnt/data/config/rclone.conf
export RCLONE_ADDR=localhost:61805
DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf 2>/dev/null | sed "s/.*\[//g;s/\].*//g;s/\r$//")"

if [ "${REMOTE_PATH}" = "auto" ]; then
    if [ "${DRIVE_NAME_AUTO}" = "" ]; then
        sleep 15
        exit 0
    fi
    WEBDAV_PATH=${DRIVE_NAME_AUTO}:/
else
    WEBDAV_PATH=${REMOTE_PATH}
fi

# Run rclone
exec /workdir/4* serve webdav ${WEBDAV_PATH}
