#!/bin/sh

sleep 3
DRIVE_NAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"

DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/.*\[//g;s/\].*//g")"
if [ "${DRIVE_NAME}" = "auto" ]; then
    DRIVENAME=${DRIVE_NAME_AUTO}
else
    DRIVENAME=${DRIVE_NAME}
fi

# Run rclone
htpasswd -csb /workdir/htpasswd_webdav ${GLOBAL_USER} ${GLOBAL_PASSWORD}
exec 2>&1
exec /workdir/4* serve webdav ${DRIVENAME}:/ \
--htpasswd=/workdir/htpasswd_webdav \
--addr=localhost:61805 \
--buffer-size 4M \
--config /tmp/4*.conf \
--use-mmap \
--vfs-cache-mode writes
