#!/bin/sh

DRIVE_NAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"

DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/\[//g;s/\]//g;s/\r//g")"
if [ "${DRIVE_NAME}" = "auto" ]; then
    DRIVENAME=${DRIVE_NAME_AUTO}
else
    DRIVENAME=${DRIVE_NAME}
fi

EXEC=$(head /dev/urandom | cksum | md5sum | cut -c 1-5)
TMP=$(head /dev/urandom | cksum | md5sum | cut -c 1-4)
ln -s /mnt/data/config/rclone.conf /tmp/5${TMP}.conf
cp /workdir/4* /usr/bin/${EXEC}

# Run rclone
htpasswd -csb /workdir/htpasswd_webdav ${GLOBAL_USER} ${GLOBAL_PASSWORD}
exec 2>&1
exec ${EXEC} serve webdav ${DRIVENAME}:/ \
--htpasswd=/workdir/htpasswd_webdav \
--addr=localhost:61805 \
--buffer-size 4M \
--config /tmp/5${TMP}.conf \
--use-mmap \
--vfs-cache-mode writes
