#!/bin/bash

export LS_OPTIONS='--color=auto'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
export PS1='\w$ '
export HOME=/mnt/data
alias dlpr="yt-dlp --exec ytdlptorclone.sh -P /mnt/data/videos"
alias dlptg="yt-dlp --exec ytdlpuptg.sh -P /mnt/data/videos"
alias gdlr="gallery-dl -c /mnt/data/config/gallery-dl.conf --exec-after '/workdir/gdltorclone.sh {}'"
cd
