#!/bin/sh

exec 2>&1

if [ ! -f "/mnt/data/config/bashrc" ]; then
    cp /workdir/bashrc /mnt/data/config/
fi

TELEGRAM_TITLE="$(grep ^telegram-notification-title "/mnt/data/config/script.conf" | cut -d= -f2- | sed "s|^[ \t]*||g;s|\r$||")"

exec ttyd -i 127.0.0.1 -p 61803 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc
