#!/bin/sh

# Configure filebrowser
touch /mnt/data/config/filebrowser.yaml

if [ ! -f "/mnt/data/config/filebrowser.db" ]; then
    filebrowser -d /mnt/data/config/filebrowser.db config init -c /mnt/data/config/filebrowser.yaml
    filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps" -c /mnt/data/config/filebrowser.yaml
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} --locale zh-cn -c /mnt/data/config/filebrowser.yaml
    fi
else
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --locale zh-cn --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps" -c /mnt/data/config/filebrowser.yaml
    else
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps" -c /mnt/data/config/filebrowser.yaml
    fi
    filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} -p ${GLOBAL_PASSWORD} -c /mnt/data/config/filebrowser.yaml
fi

filebrowser -d /mnt/data/config/filebrowser.db config set -r /mnt/data -b ${GLOBAL_PORTAL_PATH}/files -p 61801 -c /mnt/data/config/filebrowser.yaml

# Run filebrowser
exec 2>&1
exec filebrowser -d /mnt/data/config/filebrowser.db -c /mnt/data/config/filebrowser.yaml
