#!/bin/sh

# Configure filebrowser
if [ ! -f "/mnt/data/config/filebrowser.db" ]; then
    filebrowser -d /mnt/data/config/filebrowser.db config init -c /mnt/data/config/filebrowser.yaml
    filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps,yt-dlp,gallery-dl,gdlr,dlpr"
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} --locale zh-cn
    fi
else
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --locale zh-cn --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps,yt-dlp,gallery-dl,gdlr,dlpr"
    else
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps,yt-dlp,gallery-dl,gdlr,dlpr"
    fi
    filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} -p ${GLOBAL_PASSWORD}
fi

filebrowser -d /mnt/data/config/filebrowser.db config set -r /mnt/data -b ${GLOBAL_PORTAL_PATH}/files -p 61801

# Run filebrowser
exec 2>&1
exec filebrowser -d /mnt/data/config/filebrowser.db
