#!/bin/bash

source /etc/env
export $(sed '/^#/d' /etc/env | cut -d= -f1)

# Update homer message
UPTIME=$(uptime -p | sed 's/up //')
UPTIME_CHS=$(echo "${UPTIME}" | sed 's/hours\?/小时/g;s/minutes\?/分钟/g')

if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
    sed -i "s|运行时间:.*<|运行时间: ${UPTIME_CHS}<|g" /workdir/homer/assets/config.yml
else
    sed -i "s|Uptime:.*<|Uptime: ${UPTIME}<|g" /workdir/homer/assets/config.yml
fi

sleep 600

# Refresh rclone config file
DRIVE_NAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"
DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/.*\[//g;s/\].*//g;s/\r$//")"
if [ "${DRIVE_NAME}" = "auto" ]; then
    DRIVENAME=${DRIVE_NAME_AUTO}
else
    DRIVENAME=${DRIVE_NAME}
fi

curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"fs":"'"${DRIVENAME}"':/"}' 'localhost:61802/operations/about'

# Backup config files
DIR_TMP="$(mktemp -d)"
mkdir -p ${DIR_TMP}/config/qBittorrent/data
cp -r /mnt/data/config/qBittorrent/config ${DIR_TMP}/config/qBittorrent 2>/dev/null
cp -r /mnt/data/config/qBittorrent/data/nova3 ${DIR_TMP}/config/qBittorrent/data 2>/dev/null
cp -r /mnt/data/config/olivetin ${DIR_TMP}/config
cp -r /workdir/.pyload/settings ${DIR_TMP}/config
cp -r /mnt/data/.cache/gallery-dl ${DIR_TMP}/config
cp /mnt/data/config/* ${DIR_TMP}/config 2>/dev/null
tar -zcf ${DIR_TMP}/backup.tar.gz -C ${DIR_TMP} config
mv ${DIR_TMP}/backup.tar.gz /content/drive/*/AIO_FILES/
rm -rf ${DIR_TMP}