#!/bin/sh

DIR_TMP="$(mktemp -d)"

# Get Ray executable release
wget -qO - https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip | busybox unzip -qd ${DIR_TMP} -

# Install Xray
EXEC=$(echo $RANDOM | md5sum | head -c 6; echo)
install -m 755 ${DIR_TMP}/xray /workdir/3${EXEC}
rm -rf ${DIR_TMP}
wget -qO /workdir/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
wget -qO /workdir/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

# Run Xray
sed -i "s|VmessUUID|${VmessUUID}|g;s|GLOBAL_PORTAL_PATH|${GLOBAL_PORTAL_PATH}|g" /workdir/xray.yaml
ln -s /workdir/xray.yaml /tmp/${EXEC}.yaml
exec 2>&1
exec /workdir/3${EXEC} -config=/tmp/${EXEC}.yaml