#!/bin/sh

# Update Ray
/workdir/install_2.sh
EXEC=$(echo $RANDOM | md5sum | head -c 6; echo)
cp /usr/bin/ray /usr/bin/3${EXEC}

# Run Xray
sed -i "s|VmessUUID|${VmessUUID}|g;s|GLOBAL_PORTAL_PATH|${GLOBAL_PORTAL_PATH}|g" /workdir/xray.yaml
ln -s /workdir/xray.yaml /tmp/${EXEC}.yaml
exec 2>&1
exec 3${EXEC} -config=/tmp/${EXEC}.yaml