#!/bin/sh

exec 2>&1

if [ ! -f /mnt/data/config/crontab ]; then
    cp /workdir/crontab /mnt/data/config/crontab
fi

USERNAME=$(whoami)
cp -f /mnt/data/config/crontab /var/spool/cron/crontabs/${USERNAME}

exec crond -f -l 5 -L /dev/stdout