#!/bin/sh

exec 2>&1
pipx upgrade --pip-args='--pre --no-cache-dir' pyload-ng

if [ -f "/mnt/data/config/aria2/tracker.sh" ]; then
    /mnt/data/config/aria2/tracker.sh RPC localhost:61800 ${GLOBAL_PASSWORD}
    exec sleep 24h
else
    exec sleep 24h
fi