#!/bin/sh

exec 2>&1

pipx upgrade --pip-args='--no-cache-dir' gallery-dl

# Refresh rclone config file
DRIVE_NAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"
DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/.*\[//g;s/\].*//g;s/\r$//")"
if [ "${DRIVE_NAME}" = "auto" ]; then
    DRIVENAME=${DRIVE_NAME_AUTO}
else
    DRIVENAME=${DRIVE_NAME}
fi

curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"fs":"'"${DRIVENAME}"':/"}' 'localhost:61802/operations/about'

# Update Aria2 tracker list
if [ -f "/mnt/data/config/aria2/tracker.sh" ]; then
    /mnt/data/config/aria2/tracker.sh RPC localhost:61800 ${GLOBAL_PASSWORD}
    exec sleep 24h
else
    exec sleep 24h
fi
