#!/bin/sh

exec 2>&1
pip install --no-cache-dir pyload-ng[plugins] -U
mkdir -p /workdir/.pyload/settings /workdir/Downloads/pyLoad  2>/dev/null

if [ ! -f "/workdir/.pyload/settings/pyload.cfg" ]; then
    cp /workdir/pyload.cfg /workdir/.pyload/settings/pyload.cfg
fi

if [ ! -d "/mnt/data/config/pyload" ]; then
    ln -s /workdir/.pyload/settings /mnt/data/config/pyload
fi

sed -i "s|str\ prefix\ :\ \"Path prefix\"\ =.*|str\ prefix\ :\ \"Path prefix\"\ =\ ${GLOBAL_PORTAL_PATH}/pyload|g" /workdir/.pyload/settings/pyload.cfg
sed -i 's|delete\"\ =.*|delete"\ =\ False|g' /workdir/.pyload/settings/plugins.cfg 2>/dev/null
EXEC=$(echo $RANDOM | md5sum | head -c 6; echo)
mv /usr/local/bin/1* /usr/local/bin/1${EXEC}
ln -s /workdir/Downloads/pyLoad /mnt/data/pyload_downloads
export HOME=/workdir
cd

# Run pyload
exec /usr/local/bin/1${EXEC}