#!/bin/bash

source /etc/env
export $(sed '/^#/d' /etc/env | cut -d= -f1)

mkdir -p /workdir/.pyload/settings /workdir/Downloads/pyLoad  2>/dev/null

if [ ! -f "/workdir/.pyload/settings/pyload.cfg" ]; then
    cp /workdir/pyload.cfg /workdir/.pyload/settings/pyload.cfg
fi

if [ ! -d "/mnt/data/config/pyload" ]; then
    ln -s /workdir/.pyload/settings /mnt/data/config/pyload
fi

sed -i "s|str\ prefix\ :\ \"Path prefix\"\ =.*|str\ prefix\ :\ \"Path prefix\"\ =\ ${GLOBAL_PORTAL_PATH}/pyload|g" /workdir/.pyload/settings/pyload.cfg
sed -i 's|delete\"\ =.*|delete"\ =\ False|g' /workdir/.pyload/settings/plugins.cfg 2>/dev/null
export HOME=/workdir
cd

# Run pyload
exec 2>&1
exec /usr/local/bin/1*