#!/bin/sh

# Configure AriaNG & Rclone WebUI
sed -i 's|rpcInterface:"jsonrpc"|rpcInterface:"'"${GLOBAL_PORTAL_PATH/\//}"'/jsonrpc"|g' /workdir/ariang/js/aria-ng-a87a79b0e7.min.js
sed -i 's|ipAddress:a|ipAddress:`${window.location.protocol}//${window.location.hostname}'"${GLOBAL_PORTAL_PATH}"'/rclonerc`|g' /workdir/rcloneweb/build/static/js/3.90421092.chunk.js

# Configure homer
cp /workdir/homer_conf/* /workdir/homer/assets/tools/
cp /workdir/homer_conf/homer_${GLOBAL_LANGUAGE}.yml /workdir/homer/assets/config.yml
sed -i "s|GLOBAL_PORTAL_PATH|${GLOBAL_PORTAL_PATH}|g" /workdir/homer/assets/config.yml

# Configure Caddyfile
if [ ! -f "/mnt/config/caddy/Caddyfile" ]; then
  mkdir -p /mnt/config/caddy
  cp /workdir/Caddyfile /mnt/config/caddy/Caddyfile
fi

HASH="$(caddy hash-password --plaintext ${GLOBAL_PASSWORD})"
sed -i "s|HASH|${HASH}|g" /mnt/config/caddy/Caddyfile

# Run caddy
exec 2>&1
exec caddy run --config /workdir/Caddyfile --adapter caddyfile
