#!/bin/bash

exec 2>&1

# Configure AriaNG & Rclone WebUI
sed -i 's|rpcInterface:"jsonrpc"|rpcInterface:"'"${GLOBAL_PORTAL_PATH/\//}"'/jsonrpc"|g' /workdir/ariang/js/aria-ng*.min.js
sed -i 's|ipAddress:a|ipAddress:`${window.location.protocol}//${window.location.hostname}'"${GLOBAL_PORTAL_PATH}"'/rclonerc`|g' /workdir/rcloneweb/build/static/js/3.90421092.chunk.js

# Configure homer
cp /workdir/homer_conf/* /workdir/homer/assets/tools/

# Configure Caddyfile
HASH="$(caddy hash-password --plaintext ${GLOBAL_PASSWORD})"
sed -i "s|HASH|${HASH}|g" /workdir/Caddyfile

# Run caddy
exec caddy run --config /workdir/Caddyfile --adapter caddyfile
