#!/bin/bash

source /etc/env
export $(sed '/^#/d' /etc/env | cut -d= -f1)

# Configure AriaNG & Rclone WebUI
sed -i 's|rpcInterface:"jsonrpc"|rpcInterface:"'"${GLOBAL_PORTAL_PATH/\//}"'/jsonrpc"|g' /workdir/ariang/js/aria-ng-3fcc0271ed.min.js
sed -i 's|ipAddress:a|ipAddress:`${window.location.protocol}//${window.location.hostname}'"${GLOBAL_PORTAL_PATH}"'/rclonerc`|g' /workdir/rcloneweb/build/static/js/3.90421092.chunk.js

# Configure homer
cp /workdir/homer_conf/* /workdir/homer/assets/tools/
cp /workdir/homer_conf/homer_${GLOBAL_LANGUAGE}.yml /workdir/homer/assets/config.yml
sed -i "s|GLOBAL_PORTAL_PATH|"${GLOBAL_PORTAL_PATH}"|g" /workdir/homer/assets/config.yml

if [ "${PYLOAD_INSTALL}" = "Disable" ]; then
    LINE=$(sed -n -e '/pyLoad/=' /workdir/homer/assets/config.yml)
    LINE2=$((LINE + 5))
    sed -i "${LINE},${LINE2}d" /workdir/homer/assets/config.yml
fi

# Run caddy
exec 2>&1
exec caddy run --config /workdir/Caddyfile --adapter caddyfile
